@RealEstate_Dapper.Api_HostAddress = https://localhost:44377

GET {{RealEstate_Dapper.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{RealEstate_Dapper.Api_HostAddress}}/api/products

###

GET {{RealEstate_Dapper.Api_HostAddress}}/api/popularlocations

###
